# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\xd8\x01\n\x12\x41ppendEntryRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12/\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x1e.raft.AppendEntryRequest.Entry\x12\x15\n\rleaseDuration\x18\x06 \x01(\x02\x12\x14\n\x0cleaderCommit\x18\x07 \x01(\x05\x1a\x19\n\x05\x45ntry\x12\x10\n\x08\x63ommands\x18\x01 \x03(\t\"4\n\x13\x41ppendEntryResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x05\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x05\x32\x9a\x01\n\x0craft_service\x12\x44\n\x0b\x61ppendEntry\x12\x18.raft.AppendEntryRequest\x1a\x19.raft.AppendEntryResponse\"\x00\x12\x44\n\x0brequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPENDENTRYREQUEST']._serialized_start=21
  _globals['_APPENDENTRYREQUEST']._serialized_end=237
  _globals['_APPENDENTRYREQUEST_ENTRY']._serialized_start=212
  _globals['_APPENDENTRYREQUEST_ENTRY']._serialized_end=237
  _globals['_APPENDENTRYRESPONSE']._serialized_start=239
  _globals['_APPENDENTRYRESPONSE']._serialized_end=291
  _globals['_REQUESTVOTEREQUEST']._serialized_start=293
  _globals['_REQUESTVOTEREQUEST']._serialized_end=391
  _globals['_REQUESTVOTERESPONSE']._serialized_start=393
  _globals['_REQUESTVOTERESPONSE']._serialized_end=449
  _globals['_RAFT_SERVICE']._serialized_start=452
  _globals['_RAFT_SERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
